#!/bin/sh
#SBATCH --job-name=opcuda
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --partition=3090,q4

echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"
echo "Starting job $SLURM_JOB_ID at " `date`
echo "Running on nodes: $SLURM_NODELIST"

start=$(date +%s)
module load intel/2020
module load cuda/11.8-share
source /data/home/wuxingxing/anaconda3/etc/profile.d/conda.sh
conda activate matpl-2026.3
source /data/home/wuxingxing/xcode/qnep/env.sh


MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
#MASTER_PORT=12355

# 动态分配空闲端口
function get_free_port() {
    python -c 'import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'
}
MASTER_PORT=$(get_free_port)

export MASTER_ADDR=$MASTER_ADDR
export MASTER_PORT=$MASTER_PORT


MATPL train train.json  # 您的训练命令


echo "Job $SLURM_JOB_ID done at " `date`

end=$(date +%s)
take=$(( end - start ))
echo Time taken to execute commands is ${take} seconds
exit 0
