#!/bin/sh
#SBATCH --job-name=asedp
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --gpus-per-task=1
#SBATCH --partition=3080ti

echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"

start=$(date +%s)
#module load intel/2020

source /share/app/MATPL/MatPL-2026.3/env.sh

#module load cuda/11.8-share
#source /data/home/wuxingxing/anaconda3/etc/profile.d/conda.sh
#conda activate matpl-2026.3
#source ~/xcode/qnep-elec/env.sh
python ase_test.py

