#!/bin/sh
#SBATCH --job-name=nepmn
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --partition=3080ti

echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"
echo "Starting job $SLURM_JOB_ID at " `date`
echo "Running on nodes: $SLURM_NODELIST"

start=$(date +%s)
source /share/app/MATPL/MatPL-2026.3/env.sh
#source /data/home/wuxingxing/anaconda3/etc/profile.d/conda.sh
#conda activate matpl-2026.3
which python

#export PYTHONPATH=/share/app/MATPL/MatPL-2026.3:$PYTHONPATH
#export PATH=/share/app/MATPL/MatPL-2026.3/src/bin:$PATH
#module load cuda/11.8-share intel/2020

MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
# 动态分配空闲端口
function get_free_port() {
    python -c 'import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'
}
MASTER_PORT=$(get_free_port)

export MASTER_ADDR=$MASTER_ADDR
export MASTER_PORT=$MASTER_PORT

echo "addrs: $MASTER_ADDR"
echo "port:  $MASTER_PORT"
echo "tasks: $SLURM_NTASKS"

echo $PYTHONPATH

MATPL train train.json

echo "Job $SLURM_JOB_ID done at " `date`

end=$(date +%s)
take=$(( end - start ))
echo Time taken to execute commands is ${take} seconds
exit 0
