#!/bin/sh
#SBATCH --job-name=hfo2md
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --gpus-per-task=1
#SBATCH --partition=gpu
echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"

# 替换为自己的安装路径
source /share/app/MATPL/MatPL-2026.3/env.sh

mpirun -np 4 lmp_mpi -in in.lammps

end=$(date +%s)
take=$(( end - start ))


