#!/bin/sh
#SBATCH --job-name=hfo2md
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --gpus-per-task=1
#SBATCH --partition=3080ti,3090,q4
echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"
module load lammps4matpl/2026.3

mpirun -np 4 lmp -k on g 4 -sf kk -pk kokkos -in in.lmp-kk

end=$(date +%s)
take=$(( end - start ))


