#!/bin/sh
#SBATCH --job-name=hfo2md
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=cpu
echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"

module load intel/2020 
# 替换路径为自己的安装matpl-env.sh 路径
source /share/app/MATPL/MatPL-2025.3/matpl-env.sh
# 26版本暂不支持纯cpu 运行
mpirun -np 4 lmp_mpi -in in.lmp-25

end=$(date +%s)
take=$(( end - start ))


