#!/bin/sh
#SBATCH --job-name=hfo2md
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --gpus-per-task=1
#SBATCH --partition=gpu
echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"
module load cuda/11.8 openmpi/4.1.6
source /share/app/MATPL/MatPL-2026.3/env.sh # 替换路径为自己的安装matpl-env.sh 路径

mpirun -np 1 lmp -k on g 1 -sf kk -pk kokkos -in kkin.lmp


end=$(date +%s)
take=$(( end - start ))


